blank_issues_enabled: false
contact_links:
  - name: ğŸŒ KeyClicker Official Website
    url: https://wangchujiang.com/key-clicker/
    about: Introduction to the KeyClicker app on the official website!